# Generated by Django 3.2.18 on 2023-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest_booking',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='guest_booking',
            name='l_name',
        ),
        migrations.AddField(
            model_name='guest_booking',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest_booking',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest_booking',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
