# Generated by Django 3.2.18 on 2023-06-26 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingsystem', '0002_auto_20230528_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guest_booking',
            new_name='GuestBooking',
        ),
    ]
